### PR TITLE
Add portable simd (core::simd) implementation

### PR DESCRIPTION
**Pull request by Licenser**
This adds experimental 128- and 256-bit `core::simd` (rusts portable simd) implementations. Since portable simd is a nightly-only feature, it is guarded behind the `portable_public_imp` feature flag. The implementations are accessible via  the `simdutf8::basic::imp::portable::simd128` and `simdutf8::basic::imp::portable::simd256` modules.

### CODE REVIEW

**Comment by hkratz** [comment]
@Licenser Sorry for being unresponsive for the last year. Now I am finally picking up on this. I hope you don't mind me fixing it up a bit before merging.

**Comment by Licenser** [comment]
Hey, no worries, I've been doing OSS for long enough to have all the understanding in the world for things taking time :(

**Comment by hkratz** [comment]
@Licenser Using a 128-bit portable simd implementation is only a few percent slower on ARM64 than the implementation using native intrinsics:

CleanShot 2024-09-29 at 13 12 22@2x

**Comment by Licenser** [comment]
That's pretty neat!

**Comment by hkratz** [comment]
@Licenser I will be merging this but I might create an experimental `#![forbid(unsafe_code)]` simdutf8-portable crate as well.

**Pull request merged**
