### PR TITLE
aarch64 support with nightly Rust (prototype)

### PR DESCRIPTION
**Pull request by hkratz**
So it turns out all the necessary intrinsics are there and after the big refactoring today adding aarch64 support was quite easy.

The unit tests on my Raspberry Pi 4 are the only testing it has got. As Linus famously said: "If it compiles, it is good; if it boots up, it is perfect."

### CODE REVIEW

**Comment by lemire** [comment]
Apple M1.

```
❯ RUSTUP_UPDATE_ROOT=https://dev-static.rust-lang.org/rustup sh <(curl --proto '=https' --tlsv1.2 -sSf https://dev-static.rust-lang.org/rustup/rustup-init.sh) --default-toolchain nightly
❯ cargo +nightly test
   Compiling simdutf8 v0.1.1 (/Users/lemire/CVS/github/simdutf8)
    Finished test [unoptimized + debuginfo] target(s) in 0.72s
     Running unittests (target/debug/deps/simdutf8-58005d61f60f3ab6)

running 5 tests
test tests::incomplete_on_32nd_byte ... ok
test tests::incomplete_on_64th_byte_65_bytes_total ... ok
test tests::incomplete_on_64th_byte ... ok
test tests::simple_invalid ... ok
test tests::simple_valid ... ok

test result: ok. 5 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests simdutf8

running 2 tests
test src/lib.rs - (line 34) ... ok
test src/lib.rs - (line 25) ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.41s


```


I tried the benchmarking but it seems to output lots of useless HTML pages. Do you have the command that you are using to get your benchmark numbers?

**Comment by hkratz** [comment]
> Do you have the command that you are using to get your benchmark numbers?

```
cargo install critcmp # https://github.com/BurntSushi/critcmp
cd bench

# each one of the benchmarks takes about 15 min.
cargo bench --bench=throughput_std -- --noplot --save-baseline std
cargo bench --bench=throughput_basic -- --noplot --save-baseline basic
cargo bench --bench=throughput_simdjson --features=simdjson -- --noplot --save-baseline simdjson

critcmp std basic simdjson
```

**Comment by hkratz** [comment]
Unfortunately code generation leave something to be desired. Just analyzed it for the ASCII shortcut and this is what happens:
```
# main loop with ascii check

.LBB8_2:
 orr     v5.16b, v5.16b, v19.16b         # error aggregation
 add     x9, x9, #64                     # advance index 64 bytes
 cmp     x9, x8                          # at end?
 b.hs    .LBB8_8                         # yes, exit loop
.LBB8_3:
 add     x11, x0, x9                     # advance data ptr
 ldp     q20, q21, [x11]                 # load 32 bytes into q20/q21
 ldp     q22, q23, [x11, #32]            # load 32 bytes into q22/q23
 stp     q20, q21, [sp]                  # ??? store q20/q21 on the stack ???
 orr     v20.16b, v21.16b, v20.16b       # or all chunks together
 orr     v20.16b, v20.16b, v22.16b       # or all chunks together
 orr     v20.16b, v20.16b, v23.16b       # or all chunks together
 umaxv   b20, v20.16b                    # get max byte of vec reg
 fmov    w11, s20                        # move from vec reg in gp reg
 stp     q22, q23, [sp, #32]             # ??? store q22/q23 on the stack ???
 tbz     w11, #7, .LBB8_2                # loop if high bit of max byte is zero (=> ASCII)
```
Not idea why it spills those on the stack.

**Comment by lemire** [comment]
```
# each one of the benchmarks takes about 15 min.
```

My experience has been that easy-to-run and convenient benchmarks make for faster code. It seems like 15 mins per command is qu

**Comment by lemire** [comment]
Here are my results (Apple M1, MacBook Pro). I would encourage you to streamline the benchmarking: I can't think of a good reason why it should take more than 10 seconds and it takes an hour. Anyhow, the results are not bad but there are some oddities that would need to be examined.



```

group                basic                                    simdjson                                 std
-----                -----                                    --------                                 ---
0-empty/000000       1.49      1.9±0.01ns        ? ?/sec      2.15      2.7±0.02ns        ? ?/sec      1.00      1.3±0.01ns        ? ?/sec
1-latin/000001       1.15      2.8±0.03ns   346.0 MB/sec      4.58     11.0±0.40ns    87.0 MB/sec      1.00      2.4±0.03ns   398.6 MB/sec
1-latin/000008       1.00      4.5±0.04ns  1680.3 MB/sec      1.90      8.6±0.05ns   885.1 MB/sec      1.11      5.0±0.17ns  1512.3 MB/sec
1-latin/000064       1.00      2.3±0.15ns    26.0 GB/sec      2.51      5.7±0.03ns    10.4 GB/sec      1.92      4.4±0.15ns    13.5 GB/sec
1-latin/000512       1.00      6.5±0.03ns    73.6 GB/sec      1.68     10.9±0.06ns    43.9 GB/sec      2.05     13.3±0.17ns    35.9 GB/sec
1-latin/004096       1.07     47.5±0.83ns    80.4 GB/sec      1.00     44.4±0.33ns    85.9 GB/sec      2.71    120.5±1.54ns    31.7 GB/sec
1-latin/065536       1.00    660.6±5.64ns    92.4 GB/sec      1.01   664.0±88.71ns    91.9 GB/sec      3.18      2.1±0.02µs    29.0 GB/sec
1-latin/131072       1.00   1330.1±9.09ns    91.8 GB/sec      1.05  1401.9±1402.89ns    87.1 GB/sec    3.19      4.2±0.04µs    28.7 GB/sec
2-cyrillic/000002    3.57      9.0±0.19ns   211.8 MB/sec      6.30     15.9±0.19ns   120.1 MB/sec      1.00      2.5±0.03ns   756.6 MB/sec
2-cyrillic/000008    1.76     10.5±0.35ns   727.4 MB/sec      2.37     14.1±4.38ns   540.6 MB/sec      1.00      6.0±0.05ns  1279.2 MB/sec
2-cyrillic/000065    1.00     15.3±0.18ns     4.0 GB/sec      1.40     21.4±0.15ns     2.8 GB/sec      2.61     40.1±0.42ns  1547.8 MB/sec
2-cyrillic/000513    1.00     63.0±2.46ns     7.6 GB/sec      1.00     63.2±0.28ns     7.6 GB/sec      4.71    296.7±2.75ns  1649.1 MB/sec
2-cyrillic/004096    1.14    448.7±4.54ns     8.5 GB/sec      1.00    394.5±1.74ns     9.7 GB/sec      6.04      2.4±0.07µs  1640.4 MB/sec
2-cyrillic/065536    1.12      6.9±0.13µs     8.9 GB/sec      1.00      6.1±0.04µs     9.9 GB/sec      10.76    66.1±1.08µs   944.9 MB/sec
2-cyrillic/131072    1.11     13.8±0.42µs     8.9 GB/sec      1.00     12.5±0.20µs     9.8 GB/sec      11.15   138.8±1.73µs   900.3 MB/sec
3-chinese/000003     2.78      9.0±0.05ns   319.2 MB/sec      5.36     17.3±0.24ns   165.7 MB/sec      1.00      3.2±0.09ns   888.7 MB/sec
3-chinese/000009     1.53     10.5±0.06ns   814.5 MB/sec      2.30     15.9±0.10ns   540.4 MB/sec      1.00      6.9±0.05ns  1242.9 MB/sec
3-chinese/000066     1.00     15.1±0.09ns     4.1 GB/sec      1.41     21.3±0.33ns     2.9 GB/sec      3.18     48.0±0.38ns  1310.7 MB/sec
3-chinese/000512     1.01     54.1±0.41ns     8.8 GB/sec      1.00     53.8±0.26ns     8.9 GB/sec      6.11    328.8±4.52ns  1484.9 MB/sec
3-chinese/004096     1.11    441.1±2.64ns     8.6 GB/sec      1.00    398.3±6.70ns     9.6 GB/sec      6.60      2.6±0.02µs  1487.2 MB/sec
3-chinese/065538     1.09      6.8±0.13µs     9.0 GB/sec      1.00      6.2±0.24µs     9.8 GB/sec      6.74     41.8±0.20µs  1493.7 MB/sec
3-chinese/131072     1.10     13.5±0.10µs     9.1 GB/sec      1.00     12.3±0.25µs     9.9 GB/sec      6.83     83.9±0.37µs  1490.4 MB/sec
4-emoji/000003       2.60      9.0±0.05ns   319.3 MB/sec      4.91     16.9±0.42ns   169.0 MB/sec      1.00      3.4±0.02ns   829.6 MB/sec
4-emoji/000011       1.42     11.2±0.06ns   938.8 MB/sec      2.15     16.9±0.15ns   622.3 MB/sec      1.00      7.9±0.14ns  1335.1 MB/sec
4-emoji/000067       1.00     15.5±0.11ns     4.0 GB/sec      1.41     21.8±0.25ns     2.9 GB/sec      2.01     31.2±0.27ns     2.0 GB/sec
4-emoji/000515       1.00     61.5±0.34ns     7.8 GB/sec      1.03     63.2±0.66ns     7.6 GB/sec      3.75    230.7±3.19ns     2.1 GB/sec
4-emoji/004099       1.12    443.2±7.11ns     8.6 GB/sec      1.00    394.4±3.21ns     9.7 GB/sec      4.51  1780.1±15.27ns     2.1 GB/sec
4-emoji/065538       1.13      6.7±0.04µs     9.0 GB/sec      1.00      6.0±0.04µs    10.2 GB/sec      4.75     28.3±0.24µs     2.2 GB/sec
4-emoji/131072       1.13     13.5±0.07µs     9.1 GB/sec      1.00     11.9±0.07µs    10.3 GB/sec      4.77     56.7±0.49µs     2.2 GB/sec
x-error/065536       3028.91     6.7±0.04µs        ? ?/sec    2679.45     5.9±0.04µs        ? ?/sec    1.00      2.2±0.04ns        ? ?/sec

```

**Comment by hkratz** [comment]
> Here are my results (Apple M1, MacBook Pro). I would encourage you to streamline the benchmarking: I can't think of a good reason why it should take more than 10 seconds and it takes an hour. Anyhow, the results are not bad but there are some oddities that would need to be examined.

@lemire Thanks for benchmarking on the Apple M1, despite it taking so long! I will reduce the benchmarking time or add a `_quick` variant.

The code generator is doing very weird things on aarch64 in the non-ASCII case which I cannot really work around:
- It does not unroll [this loop](https://github.com/rusticstuff/simdutf8/blob/b87e9b7fc82564f5f0c5f9ba7bf0ada5b74b158e/src/implementation/algorithm.rs#L212). `input.vals` is an array with 4 elements.
- If I unroll it by hand it decides to totally mess up the code, no longer using vectored loads or shifts.
- Some unnecessary spilling is going on even in the loop version.

The intrinsics will be [updated in a few weeks or so](https://github.com/rust-lang/rust/pull/83278), then I will have a look again. 

For now I will just put the aarch64 support behind a feature gate (Rust's conditional compilation) in the main branch so people can use it as it is.

**Comment by lemire** [comment]
> It does not unroll this loop. input.vals is an array with 4 elements.

But it does under x64, right? 

If you look at the C++ code in simdjson, you will find lots of ugly, constructions, with explicitly unrolled code... I did that to convince Visual Studio to behave a bit better. It tends to spill out quite a bit.

I'd expect the Rust compiler to be better behaved, but if NEON support is new, maybe it needs a bit of care.


It seems that you might have the chance to reduce the issue and report it to the maintainers if it does not get fixed on its own.

**Comment by hkratz** [comment]
> > It does not unroll this loop. input.vals is an array with 4 elements.
> 
> But it does under x64, right?

Yes, the assembly is the same no matter how I choose to write the loop or if I unroll it myself. The x64 SIMD code generation seems quite robust and simple changes usually don't change the assembly at all. When I [put in an abstraction layer](https://github.com/rusticstuff/simdutf8/blob/b87e9b7fc82564f5f0c5f9ba7bf0ada5b74b158e/src/implementation/x86/avx2.rs#L24) like simdjson in preparation for neon support it did not change the optimized assembly for AVX 2 and SSE 4.2 _at all_ though the code does look nothing like before.

> If you look at the C++ code in simdjson, you will find lots of ugly, constructions, with explicitly unrolled code... I did that to convince Visual Studio to behave a bit better. It tends to spill out quite a bit.
> 
> I'd expect the Rust compiler to be better behaved, but if NEON support is new, maybe it needs a bit of care.
> 
> It seems that you might have the chance to reduce the issue and report it to the maintainers if it does not get fixed on its own.

I will try to reduce it to a minimal testcase reproducing the problem.

**Pull request merged**
